
@startuml
skinparam nodesep 150
skinparam linetype ortho
allowmixing


enum GenericDateTime{
    + jaar  
    + maandJaar
    + dagMaandJaar
    + dateTime
}
enum ContractType {
    + KredietContract
    + ExamenContract
    + DiplomaContract
}



@enduml
